[project]
name = "venv-data-validation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "joblib>=1.5.0",
    "pandera>=0.23.1",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
